<?php

declare(strict_types=1);

namespace Tests\Feature\Modules\InternalCommunication\Http\Controllers\V1;

use App\Enums\IDP\RoleDefaults;
use App\Integrations\InternalCommunication\Models\Tag;
use App\Models\Permission;
use Context;
use DB;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use Ramsey\Uuid\Uuid;
use Spatie\Permission\PermissionRegistrar;
use Tests\ProtectedRouteTestCase;

#[Group('internal-communication')]
#[Group('tag')]
#[Group('article')]
class TagControllerTest extends ProtectedRouteTestCase
{
    protected string $route = 'tags.index';

    protected string $permission = 'read_article';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->auth = $this->createAuthUser(RoleDefaults::FINANCER_SUPER_ADMIN, withContext: true);
    }

    /**
     * Create permissions for tags.
     */
    protected function createTagPermissions(): void
    {
        DB::table('int_communication_rh_tags')->delete();

        $tagPermissions = [
            'create_tag',
            'read_tag',
            'update_tag',
            'delete_tag',
        ];

        foreach ($tagPermissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'api']);
        }

        // Refresh permission cache
        app()->make(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    #[Test]
    public function it_can_list_tags(): void
    {

        $this->createTagPermissions();

        // Arrange - Use auth user's financer to ensure HasFinancerScope works
        $financer = $this->auth->financers->first();

        // Set context for HasFinancerScope
        Context::add('financer_id', $financer->id);

        $tag1 = Tag::create([
            'financer_id' => $financer->id,
            'label' => ['en-GB' => 'Tag 1', 'fr-BE' => 'Tag 1', 'nl-BE' => 'Tag 1', 'pt-PT' => 'Tag 1'],
        ]);
        $tag2 = Tag::create([
            'financer_id' => $financer->id,
            'label' => ['en-GB' => 'Tag 2', 'fr-BE' => 'Tag 2', 'nl-BE' => 'Tag 2', 'pt-PT' => 'Tag 2'],
        ]);

        // Act
        $response = $this->actingAs($this->auth)
            ->getJson('/api/v1/internal-communication/tags');

        // Assert
        $response->assertStatus(200)
            ->assertJsonCount(2, 'data')
            ->assertJsonFragment([
                'id' => $tag1->id,
                'financer_id' => $financer->id,
                'label' => ['en-GB' => 'Tag 1', 'fr-BE' => 'Tag 1', 'nl-BE' => 'Tag 1', 'pt-PT' => 'Tag 1'],
            ])
            ->assertJsonFragment([
                'id' => $tag2->id,
                'financer_id' => $financer->id,
                'label' => ['en-GB' => 'Tag 2', 'fr-BE' => 'Tag 2', 'nl-BE' => 'Tag 2', 'pt-PT' => 'Tag 2'],
            ]);
    }

    #[Test]
    public function it_can_show_a_tag(): void
    {
        $this->createTagPermissions();
        // Arrange - Use auth user's financer to ensure HasFinancerScope works
        $financer = $this->auth->financers->first();

        // Set context for HasFinancerScope
        Context::add('financer_id', $financer->id);

        $tag = Tag::create([
            'financer_id' => $financer->id,
            'label' => ['en-GB' => 'Test Tag', 'fr-BE' => 'Tag de Test', 'nl-BE' => 'Test Tag', 'pt-PT' => 'Test Tag'],
        ]);

        // Act
        $response = $this->actingAs($this->auth)
            ->getJson('/api/v1/internal-communication/tags/'.$tag->id);

        // Assert
        $response->assertStatus(200)
            ->assertJson([
                'data' => [
                    'id' => $tag->id,
                    'financer_id' => $financer->id,
                    'label' => ['en-GB' => 'Test Tag', 'fr-BE' => 'Tag de Test', 'nl-BE' => 'Test Tag', 'pt-PT' => 'Test Tag'],
                ],
            ]);
    }

    #[Test]
    public function it_returns_404_for_non_existent_tag(): void
    {
        $this->createTagPermissions();
        // Act
        $response = $this->actingAs($this->auth)
            ->getJson('/api/v1/internal-communication/tags/'.Uuid::uuid4()->toString());

        // Assert
        $response->assertStatus(404);
    }

    #[Test]
    public function it_can_create_a_tag(): void
    {
        $this->withoutExceptionHandling();
        $this->createTagPermissions();
        // Arrange - Use auth user's financer to ensure HasFinancerScope works
        $financer = $this->auth->financers->first();

        // Set context for activeFinancerID() to work correctly
        Context::add('financer_id', $financer->id);

        $tagData = [
            'label' => [
                'en-GB' => 'New Tag',
                'fr-BE' => 'Nouveau Tag',
                'nl-BE' => 'Nieuwe Tag',
                'pt-PT' => 'Novo Tag',
            ],
        ];

        // Act - financer_id will be auto-assigned from Context via activeFinancerID()
        $response = $this->actingAs($this->auth)
            ->postJson('/api/v1/internal-communication/tags', $tagData);

        // Assert
        $response->assertStatus(201)
            ->assertJson([
                'data' => [
                    'financer_id' => $financer->id,
                    'label' => [
                        'en-GB' => 'New Tag',
                        'fr-BE' => 'Nouveau Tag',
                        'nl-BE' => 'Nieuwe Tag',
                        'pt-PT' => 'Novo Tag',
                    ],
                ],
            ]);

        $this->assertDatabaseHas('int_communication_rh_tags', [
            'financer_id' => $financer->id,
        ]);
    }

    #[Test]
    public function it_validates_required_fields_for_tag_creation(): void
    {
        $this->createTagPermissions();
        // Act
        $response = $this->actingAs($this->auth)
            ->postJson('/api/v1/internal-communication/tags', []);

        // Assert
        $response->assertStatus(422)
            ->assertJsonValidationErrors(['label']);
    }

    #[Test]
    public function it_can_update_a_tag(): void
    {
        $this->createTagPermissions();
        // Arrange - Use auth user's financer to ensure HasFinancerScope works
        $financer = $this->auth->financers->first();

        // Set context for HasFinancerScope
        Context::add('financer_id', $financer->id);

        $tag = Tag::create([
            'financer_id' => $financer->id,
            'label' => ['en-GB' => 'Original Tag', 'fr-BE' => 'Tag Original', 'nl-BE' => 'Originele Tag', 'pt-PT' => 'Tag Original'],
        ]);

        $updateData = [
            'financer_id' => $financer->id,
            'label' => [
                'en-GB' => 'Updated Tag',
                'fr-BE' => 'Tag Mis à Jour',
                'nl-BE' => 'Bijgewerkte Tag',
                'pt-PT' => 'Tag Atualizado',
            ],
        ];

        // Act
        $response = $this->actingAs($this->auth)
            ->putJson('/api/v1/internal-communication/tags/'.$tag->id, $updateData);

        // Assert
        $response->assertStatus(200)
            ->assertJson([
                'data' => [
                    'id' => $tag->id,
                    'financer_id' => $financer->id,
                    'label' => [
                        'en-GB' => 'Updated Tag',
                        'fr-BE' => 'Tag Mis à Jour',
                        'nl-BE' => 'Bijgewerkte Tag',
                        'pt-PT' => 'Tag Atualizado',
                    ],
                ],
            ]);

        $this->assertDatabaseHas('int_communication_rh_tags', [
            'id' => $tag->id,
            'financer_id' => $financer->id,
        ]);
    }

    #[Test]
    public function it_can_delete_a_tag(): void
    {
        $this->createTagPermissions();
        // Arrange - Use auth user's financer to ensure HasFinancerScope works
        $financer = $this->auth->financers->first();

        // Set context for HasFinancerScope
        Context::add('financer_id', $financer->id);

        $tag = Tag::create([
            'financer_id' => $financer->id,
            'label' => ['en-GB' => 'Tag to Delete', 'fr-BE' => 'Tag à Supprimer', 'nl-BE' => 'Tag om te Verwijderen', 'pt-PT' => 'Tag para Eliminar'],
        ]);

        // Act
        $response = $this->actingAs($this->auth)
            ->deleteJson('/api/v1/internal-communication/tags/'.$tag->id);

        // Assert
        $response->assertStatus(204);
        $this->assertSoftDeleted('int_communication_rh_tags', ['id' => $tag->id]);
    }

    #[Test]
    public function it_returns_404_when_deleting_non_existent_tag(): void
    {
        $this->createTagPermissions();
        // Act
        $response = $this->actingAs($this->auth)
            ->deleteJson('/api/v1/internal-communication/tags/'.Uuid::uuid4()->toString());

        // Assert
        $response->assertStatus(404);
    }
}
