# Pipeline CI/CD spécialisé pour les tests WellWo API
# À intégrer dans .github/workflows/ ou pipeline CI existant

name: WellWo API Tests
description: Tests automatisés de l'intégration WellWo avec Newman

# Déclencheurs
on:
  push:
    paths:
      - 'app/Integrations/wellbeing/WellWo/**'
      - 'postman/WellWo-API.postman_collection.json'
      - 'postman/newman-wellwo-config.json'
  pull_request:
    paths:
      - 'app/Integrations/wellbeing/WellWo/**'
      - 'postman/WellWo-API.postman_collection.json'
  schedule:
    # Tests de monitoring quotidiens à 6h00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
          - production
      test_folder:
        description: 'Specific folder to test (optional)'
        required: false
        type: string

# Variables d'environnement
env:
  NEWMAN_VERSION: 'latest'
  HTMLEXTRA_VERSION: 'latest'
  NODE_VERSION: '18'

jobs:
  # Job de validation de base
  validate-collection:
    name: 'Validation Collection'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Newman and reporters
        run: |
          npm install -g newman@${{ env.NEWMAN_VERSION }}
          npm install -g newman-reporter-htmlextra@${{ env.HTMLEXTRA_VERSION }}

      - name: Validate WellWo collection
        run: |
          newman validate app/Integrations/wellbeing/WellWo/postman/WellWo-API.postman_collection.json
          echo "✅ Collection WellWo validée avec succès"

      - name: Validate Newman configuration
        run: |
          if [ ! -f "app/Integrations/wellbeing/WellWo/postman/newman-config.json" ]; then
            echo "❌ Configuration Newman manquante"
            exit 1
          fi

          if ! jq empty app/Integrations/wellbeing/WellWo/postman/newman-config.json; then
            echo "❌ Configuration Newman invalide"
            exit 1
          fi

          echo "✅ Configuration Newman validée"

  # Job des tests WellWo complets
  wellwo-api-tests:
    name: 'WellWo API Tests'
    runs-on: ubuntu-latest
    needs: validate-collection
    strategy:
      matrix:
        environment: [dev, staging]
        include:
          - environment: dev
            timeout: 10000
          - environment: staging
            timeout: 15000
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Newman and reporters
        run: |
          npm install -g newman@${{ env.NEWMAN_VERSION }}
          npm install -g newman-reporter-htmlextra@${{ env.HTMLEXTRA_VERSION }}

      - name: Create reports directory
        run: mkdir -p reports/newman

      - name: Run WellWo Health Check
        run: |
          newman run app/Integrations/wellbeing/WellWo/postman/WellWo-API.postman_collection.json \
            --environment postman/environments/${{ matrix.environment }}.postman_environment.json \
            --folder "Health Check" \
            --reporters cli,json \
            --reporter-json-export reports/newman/health-check-${{ matrix.environment }}.json \
            --timeout ${{ matrix.timeout }} \
            --delay-request 100 \
            --bail

      - name: Run WellWo Programs Tests
        run: |
          newman run app/Integrations/wellbeing/WellWo/postman/WellWo-API.postman_collection.json \
            --environment postman/environments/${{ matrix.environment }}.postman_environment.json \
            --folder "Programs" \
            --reporters cli,json,htmlextra \
            --reporter-json-export reports/newman/programs-${{ matrix.environment }}.json \
            --reporter-htmlextra-export reports/newman/programs-${{ matrix.environment }}.html \
            --timeout ${{ matrix.timeout }} \
            --delay-request 100

      - name: Run WellWo Videos Tests
        run: |
          newman run app/Integrations/wellbeing/WellWo/postman/WellWo-API.postman_collection.json \
            --environment postman/environments/${{ matrix.environment }}.postman_environment.json \
            --folder "Videos" \
            --reporters cli,json,htmlextra \
            --reporter-json-export reports/newman/videos-${{ matrix.environment }}.json \
            --reporter-htmlextra-export reports/newman/videos-${{ matrix.environment }}.html \
            --timeout ${{ matrix.timeout }} \
            --delay-request 100

      - name: Run WellWo End-to-End Tests
        run: |
          newman run app/Integrations/wellbeing/WellWo/postman/WellWo-API.postman_collection.json \
            --environment postman/environments/${{ matrix.environment }}.postman_environment.json \
            --folder "End-to-End Scenarios" \
            --reporters cli,json,htmlextra \
            --reporter-json-export reports/newman/e2e-${{ matrix.environment }}.json \
            --reporter-htmlextra-export reports/newman/e2e-${{ matrix.environment }}.html \
            --timeout ${{ matrix.timeout }} \
            --delay-request 200

      - name: Run Complete WellWo Test Suite
        if: success() || failure()
        run: |
          ./app/Integrations/wellbeing/WellWo/postman/scripts/run-tests.sh ${{ matrix.environment }}

      - name: Upload Newman Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports-${{ matrix.environment }}
          path: reports/newman/
          retention-days: 30

      - name: Parse Test Results
        if: always()
        run: |
          if [ -f "reports/newman/newman-wellwo-report.json" ]; then
            TOTAL_TESTS=$(jq '.run.stats.tests.total' reports/newman/newman-wellwo-report.json)
            FAILED_TESTS=$(jq '.run.stats.tests.failed' reports/newman/newman-wellwo-report.json)
            PASSED_TESTS=$(jq '.run.stats.tests.passed' reports/newman/newman-wellwo-report.json)

            echo "📊 Résultats des tests WellWo (${{ matrix.environment }}):"
            echo "   ✅ Tests réussis: $PASSED_TESTS"
            echo "   ❌ Tests échoués: $FAILED_TESTS"
            echo "   📈 Total: $TOTAL_TESTS"

            if [ "$FAILED_TESTS" -gt 0 ]; then
              echo "::error::$FAILED_TESTS tests ont échoué pour l'environnement ${{ matrix.environment }}"
              exit 1
            fi
          fi

  # Job de monitoring de production (optionnel)
  production-monitoring:
    name: 'Production Monitoring'
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Production Health Monitoring
        run: |
          newman run app/Integrations/wellbeing/WellWo/postman/WellWo-API.postman_collection.json \
            --environment postman/environments/production.postman_environment.json \
            --folder "Health Check" \
            --reporters cli,json \
            --reporter-json-export reports/newman/production-monitoring.json \
            --timeout 30000 \
            --delay-request 500 \
            --bail

      - name: Send Slack notification on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: '🚨 WellWo API Production Monitoring Failed'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

# Configuration des notifications
notifications:
  slack:
    on_success: change
    on_failure: always
    template:
      - "✅ WellWo API Tests: %{result} on %{branch}"
      - "📊 Build #%{build_number} - %{commit_message}"
      - "🔗 View Report: %{build_url}"