<?php

declare(strict_types=1);

namespace App\Http\Controllers\V1;

use App\Actions\Invoicing\ExportInvoicesExcelAction;
use App\Actions\Invoicing\ExportUserBillingExcelAction;
use App\Actions\Invoicing\GenerateInvoicePdfAction;
use App\Actions\Invoicing\SendInvoiceEmailAction;
use App\Http\Controllers\Controller;
use App\Http\Requests\Invoicing\ExportInvoicesExcelRequest;
use App\Http\Requests\Invoicing\SendInvoiceEmailRequest;
use App\Models\Invoice;
use Dedoc\Scramble\Attributes\Group;
use Dedoc\Scramble\Attributes\QueryParameter;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpFoundation\StreamedResponse;

#[Group('Invoicing')]
class InvoiceExportController extends Controller
{
    /**
     * Export invoices to Excel.
     *
     * Generates and downloads an Excel file containing filtered invoices with their details and items.
     * The export can be filtered by status, recipient, and billing period.
     *
     * @requestMediaType multipart/form-data
     *
     * @throws AuthorizationException
     * @throws ValidationException
     */
    public function excel(ExportInvoicesExcelRequest $request, ExportInvoicesExcelAction $action): StreamedResponse
    {
        $this->authorize('exportExcel', Invoice::class);

        return $action->execute($request->validated(), $request->user());
    }

    /**
     * Download invoice PDF.
     *
     * Generates and downloads a PDF version of the invoice.
     * The PDF can be regenerated by passing the force_regenerate query parameter.
     *
     * @throws AuthorizationException
     */
    #[QueryParameter('force_regenerate', description: 'Force PDF regeneration instead of using cached version', type: 'boolean', example: false)]
    public function pdf(Request $request, Invoice $invoice, GenerateInvoicePdfAction $action): StreamedResponse
    {
        $this->authorize('downloadPdf', $invoice);

        $force = $request->boolean('force_regenerate', false);

        return $action->execute($invoice->id, $force);
    }

    /**
     * Send invoice by email.
     *
     * Queues an email job to send the invoice PDF to the specified recipient(s).
     * The invoice PDF is attached to the email.
     *
     * @throws AuthorizationException
     * @throws ValidationException
     */
    public function sendEmail(Invoice $invoice, SendInvoiceEmailRequest $request, SendInvoiceEmailAction $action): JsonResponse
    {
        $this->authorize('sendEmail', $invoice);

        $action->execute($invoice->id, $request->getEmail(), $request->getCc());

        return response()->json(['message' => 'Invoice email queued']);
    }

    /**
     * Export user billing details to Excel.
     *
     * Generates and downloads an Excel file containing detailed billing information
     * for all users associated with this invoice. Includes breakdowns by user,
     * module usage, and prorated calculations.
     *
     * @throws AuthorizationException
     */
    public function userBilling(Invoice $invoice, ExportUserBillingExcelAction $action): StreamedResponse
    {
        $this->authorize('exportUserBilling', $invoice);

        return $action->execute($invoice->id);
    }
}
