<?php

namespace Tests\Feature\Http\Controllers\V1\RoleController;

use DB;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use Tests\Helpers\Facades\ModelFactory;
use Tests\ProtectedRouteTestCase;

#[Group('role')]

class DeleteRoleTest extends ProtectedRouteTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        // Delete dependent tables first to avoid foreign key constraints
        DB::table('role_has_permissions')->delete();
        DB::table('model_has_roles')->delete();
        DB::table('roles')->delete();
    }

    #[Test]
    public function it_can_delete_role(): void
    {

        $role = ModelFactory::createRole();

        $this->assertDatabasehas('roles', ['id' => $role['id'], 'deleted_at' => null]);

        $response = $this->delete("/api/v1/roles/{$role->id}");

        $response->assertStatus(204);

        $this->assertDatabaseMissing('roles', ['id' => $role['id'], 'deleted_at' => null]);
    }

    #[Test]
    public function a_custom_role_can_be_deleted_if_no_user_is_using_it(): void
    {

        $role = ModelFactory::createRole(['is_protected' => false]);
        $user = ModelFactory::createUser();
        $user->assignRole($role);

        $this->assertDatabasehas('roles', ['id' => $role['id'], 'deleted_at' => null]);

        $response = $this->delete("/api/v1/roles/{$role->id}");

        $response->assertStatus(422);

        $this->assertDatabaseHas('roles', ['id' => $role['id'], 'deleted_at' => null]);
    }
}
