<?php

namespace App\Providers;

use Illuminate\Support\Facades\File;
use Illuminate\Support\ServiceProvider;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

class IntegrationMigrationServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        $integrationsPath = base_path('app/Integrations');

        if (! File::exists($integrationsPath)) {
            return;
        }

        // Get all migration directories
        $migrationDirs = [];
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($integrationsPath, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($iterator as $file) {
            if ($file instanceof SplFileInfo && $file->isDir() && $file->getBasename() === 'migrations') {
                $migrationDirs[] = $file->getPathname();
            }
        }

        // Load migrations from each directory
        foreach ($migrationDirs as $migrationDir) {
            $this->loadMigrationsFrom($migrationDir);
        }
    }

    public function register(): void
    {
        parent::register(); // TODO: Change the autogenerated stub

    }
}
